### PR TITLE
ui not deleted when uninstall

### PR DESCRIPTION
**Pull request by panguicai008**

### CODE REVIEW

**Comment by SSmallMonster** [comment]
@panguicai008 Thanks for your contribution.

This is good for me, but there are some change about indentation, can we fix it at another PR?

**Comment by panguicai008** [comment]
> @panguicai008 Thanks for your contribution.
> 
> This is good for me, but there are some change about indentation, can we fix it at another PR?
there are some change about indentation，this means that the code has not been formatted. Do I need to leave a  formated mistake uncorrected, and only change my part?

**Comment by SSmallMonster** [comment]
> > @panguicai008 Thanks for your contribution.
> > This is good for me, but there are some change about indentation, can we fix it at another PR?
> 
> there are some change about indentation，this means that the code has not been formatted. Do I need to leave a formatted mistake uncorrected, and only change my part?

I think so, may be we should format all files , how do you think @buffalo1024 ?

**Comment by peng9808** [comment]
https://github.com/hwameistor/hwameistor-operator/pull/296

**Comment by peng9808** [comment]
https://github.com/hwameistor/hwameistor-operator/pull/316

**Pull request closed without merging**
